-- 0052_supplier_contact_register.sql
-- Load the supplier contact register (Excel) into the supplier master.
--
-- The register held 35 suppliers with almost nothing on them: address, contact
-- and email were empty on nearly every row, and materialCode usually named one
-- code where the supplier actually sends several. An approved-supplier list that
-- cannot say how to reach the supplier or what they are approved to send is a
-- list, not a control.
--
-- 36 rows across six sheets. Only TWO are suppliers that were missing:
--   บริษัท หมูเจริญ ฟู้ดส์เซอร์วิส จำกัด — recorded in the sheet as
--     "บริษัทปิดทำการ", so it goes in Inactive, not Approved. It belongs in the
--     register because historical receiving records point at it.
--   บริษัท ผลธัญญะ จำกัด — safety footwear, genuinely new.
-- The other 34 rows are the suppliers already here, which is the reassuring
-- answer: the register was complete, just hollow.
--
-- The sheet also finally names SP0034 — หจก.หมูสามตัว — which has been carried
-- as "ชื่อตามบันทึกหน้างาน — รอระบุชื่อนิติบุคคล" since the disqualification was
-- recorded. Its Rejected status is untouched.
--
-- Names are NOT taken from the sheet where they merely differ in transliteration
-- (อี เค ซลอทเทอร์เฮ้าส์ / อีเค ซอลเทอร์เฮาส์, กุยลิ้มซึ้ง / กุยลิ้มฮึ้ง, ท้อป
-- เมาท์เทน / ท็อป เม้าเทน). Picking a spelling is a decision about which is the
-- registered name, and that needs the company certificate, not a guess. Two
-- names ARE taken from the sheet because it is fuller rather than different:
-- SP0034 and SP0023 (…อินเตอร์เนชั่นแนล อินดัสตรี้ จำกัด).
--
-- materialCode is a UNION of what was there and what the sheet lists — the sheet
-- is more complete, but overwriting would silently drop anything it omits.
--
-- Nothing here touches approval status, risk, scope or evaluation dates. This is
-- contact and supply data; who is approved to send what is a QA decision and is
-- already recorded elsewhere.

-- ── Fill in the 31 suppliers already on the register ───────────────────────
UPDATE suppliers SET materialCode = 'RM0001, RM0002', contact = '098-1757022 · คุณโบว์', email = 'Jittranuck@betagro.com', address = 'อาคารเบทาโกรทาวเวอร์(นอร์ธปาร์ค) 323 หมู่ 6แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพฯ 10210', requiredDocs = 'ร3., รน. เอกสารรับรองฟาร์ม', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สะโพกหมู มันสันแข็ง | ขั้นต่ำ: 100.0 | ระยะเวลาจัดส่ง: 7 วัน | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0001';
UPDATE suppliers SET materialCode = 'RM0001, RM0002', contact = '034-868263 · คุณหวาน', email = 'admin@eksth.com', address = '75 หมู่ 8 ต.ท่าเสา อ.กระทุ่มแบน จ.สมุทรสาคร 74110', requiredDocs = 'ร3., รน. เอกสารรับรองฟาร์ม', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สะโพกหมู มันสันแข็ง | ขั้นต่ำ: 100.0 | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0005';
UPDATE suppliers SET materialCode = 'RM0001, RM0002', contact = '065-5284419 · คุณปรุง', address = '5/2 ซ.พลหลโยธิน 54/1 แยก6-2 แขวงคลองถนน เขตสายไหม กรุงเทพฯ 10220', requiredDocs = 'ร3., รน. เอกสารรับรองฟาร์ม', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สะโพกหมู มันสันแข็ง | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0003';
UPDATE suppliers SET materialCode = 'RM0004', contact = 'คุณกวาง', address = 'อาคารเบทาโกรทาวเวอร์(นอร์ธปาร์ค) 323 หมู่ 6 แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพฯ 10210', requiredDocs = 'ร3., รน. เอกสารรับรองฟาร์ม', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ติ่งบีบี | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0002';
UPDATE suppliers SET materialCode = 'RM0004, RM0005', contact = '081-6466162', address = '92/2 หมู่ 6 ต.นครปฐม อ.เมือง จ.นครปฐม 73000', requiredDocs = 'ร3., รน.', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ติ่งบีบี อกคู่ลอกหนัง | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0004';
UPDATE suppliers SET materialCode = 'RM0006', address = 'ต.ลำโพ อ.บางบัวทอง จ.ปทุมธานี', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ข้าวสารเหนียว | เงื่อนไขชำระเงิน: เครดิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0006';
UPDATE suppliers SET materialCode = 'PD0006, PD0025, 26, 22, 27, 28, 34, 35, PD0010, 24, 25, 29, 31, 33, 38', contact = 'คุณหมิว', address = '47 หมู่ 2 ต.บางบัวทอง อ.บางบัวทอง จ.นนทบุรี 11110', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: วุ้นเส้น,ข้าวเจ้า / ซีอิ๊วขาวเห้ดหอม,โซดา,ซอสบาบิคิว,ซอสพริก,น้ำมันงา,น้ำปลา / เกลือ,แป้งมัน,เบคกิ้งโซดา,พริกขี้หนูป่น,ผงกระหรี่,วุ้นเส้น,ข้าวสาร,งาขาว | ระยะเวลาจัดส่ง: 7 วัน | เงื่อนไขชำระเงิน: เครดิต / จ่ายเงินทันทีหลังรับสินค้า | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM, ซอสปรุงรส, เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0007';
UPDATE suppliers SET materialCode = 'RM0001, RM0002', name = 'หจก.หมูสามตัว', contact = 'คุณก้อย', address = '99/26 หมู่ 6 ต.ท่าข้าม อ.สามพราน จ.นครปฐม', requiredDocs = 'ร3,รน.', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สะโพกหมู มันสันแข็ง | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0034';
UPDATE suppliers SET materialCode = 'PD0001, 3, 4, 5', contact = '099-286-5705 YCG-FS-Setanun.roe', email = 'setanun.roe@deksomboon.com', address = '767 ซ.วัดไผ่เงิน ถ.วดไผ่เงิน แขวงทุ่งวัดดอน เขตสาทร กรุงเทพ 10120', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ซอสหอยนางรมหมู,ซอสปรุงรสฝาเขียว, ซีอิ๊วขาว สูตร 1,ซีอิ๊วขาวฉลากส้ม | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น ซอสปรุงรส — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0008';
UPDATE suppliers SET materialCode = 'PD0002', contact = '094-8546192 · คุณอุดมศักดิ์', address = '68 หมู่ 1 ต.ทุ่งกระพังโหม อ.กำแพงแสน จ.นครปฐม 73140', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ซอสหอยนางรมไก่(ตรามือ1) | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น ซอสปรุงรส — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0009';
UPDATE suppliers SET materialCode = 'PD0019', contact = '062-7168070 · คุณอัมพร', email = 'amporn.vodf@gmail.com', address = '76 อาคาร ดี.เอฟ ถนนริมคลองแสนแสบ แขวง บางกพปิ เขตห้วยขวาง หรุงเทพ 10310', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: นมจืด | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น ซอสปรุงรส — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0010';
UPDATE suppliers SET materialCode = 'PD0018', contact = '02-9217047', address = '39/6 หมู่ 11 ต.คลองข่อย อ.ปากเกร็ด จ.นนทบุรี 11120', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: น้ำตาลมะพร้าวไก่ | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น ซอสปรุงรส — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0011';
UPDATE suppliers SET materialCode = 'PD0017', contact = '081-4304692', address = '64 หมุ่ 15 ต.สวนหลวง อ.อัมพวา จ.สมุทรสาคร', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: น้ำตาลมะพร้าวหมู | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น ซอสปรุงรส — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0012';
UPDATE suppliers SET materialCode = 'PD0007', contact = '062-5495125 · คุณฟ้า', email = 'cs_industrial@jimsgroup.co.th', address = '2 ซ.เลิศนิมิตร ถ.รามคำแหง แขวงหัวหมาก เขตบางกะปิ กรุงเทพ 10240', requiredDocs = 'COA', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผงปรุงรส | ระยะเวลาจัดส่ง: 2-3 สัปดาห์ | เงื่อนไขชำระเงิน: โอนเงินก่อนสั่งผลิต | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0013';
UPDATE suppliers SET materialCode = 'PD0008', contact = 'คุณจิล', email = 'rungtiwa@iplus.co.th', address = '103 ซ.เอกชัย114(อมรพฤกษ์) ถ.เอกชัย แขวงบางบอน เขตบางบอน กรุงเทพ 10150', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผงชูรส | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0014';
UPDATE suppliers SET materialCode = 'PD0009', contact = '02-8922353', address = '24,26,28 ถ.บางบอน แขวง บางบอนเหนือ เขตบางบอน กรุงเทพ 10150', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: แป้งท้าว | ระยะเวลาจัดส่ง: 10 วัน | เงื่อนไขชำระเงิน: โอนเงินก่อนสั่งของ | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0015';
UPDATE suppliers SET materialCode = 'PD0011', address = 'ตลาดสี่มุมเมือง', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'ระยะเวลาจัดส่ง: 7 วัน | เงื่อนไขชำระเงิน: จ่ายเงินก่อนรับสินค้า (จ่ายช้าได้) | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0016';
UPDATE suppliers SET materialCode = 'PD0012, 13, 14, 15, 16, 30', contact = '086-3360605', address = '8 ซ.รามอินทรา28 แขวง ท่าแรง เขต บางเขน กรุงเทพ 10230', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: พริกไทยดำ,พริกไทยขาว,เมล็ดผักชี,ผงขมิ้น,ผงกระเทียม,ผงสามเกลอ | ระยะเวลาจัดส่ง: 7 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0017';
UPDATE suppliers SET materialCode = 'PD0030', contact = 'คุณเพียว', address = '67/42 ซอยกันตนา ถนนบางคูลัด-วัดพระเงิน ต.บางใหญ่ อ.บางใหญ่ จ.นนทบุรี 11140', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผงสามเกลอ | ระยะเวลาจัดส่ง: 14 วัน | เงื่อนไขชำระเงิน: โอนเงินก่อน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0018';
UPDATE suppliers SET materialCode = 'PD0032', contact = '02-4615080', address = '444 หมู่ 3 ถนนประชาอุทิศ ต.บ้านคลองสวน อ.พระสมุทรเจดีย์ จ.สมุทรปราการ 10290', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผงพริกหม่าล่า | ระยะเวลาจัดส่ง: 14 วัน | เงื่อนไขชำระเงิน: โอนเงินก่อน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0019';
UPDATE suppliers SET materialCode = 'PD0008', contact = '0924965691 · คุณนุช', address = 'อาคารเบทาโกรทาวเวอร์(นอร์ธปาร์ค) 323 หมู่ 6 แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพฯ 10210', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผงชูรส | เงื่อนไขชำระเงิน: เครดิต 30 วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0020';
UPDATE suppliers SET materialCode = 'PD0020, PD0021', email = 'LINE : เพื่อนครัว', address = '104/8 หมู่ 6 ถ.เชียงใหม่-ลำพูน ต.หนองหอย อ.เมือง จ.เชียงใหม่', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สีผสมอาหารแดงส้ม สีผสมอาหารเหลืองไข่ | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องปรุง — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0021';
UPDATE suppliers SET materialCode = 'PG0001, 2, 3, 4, 5, 6, PG0015, 16, PK0005, 7, 9, 11, 12, 13, 14, 15, 18, 26, 27, 28', contact = '02-5011918', address = '53/14 หมู่ 2 ถ.ติวานนท์ ต.บางกระดี อ.เมืองปทุมธานี จ.ปทุมธานี 12000', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: - ถุงหูหิ้ว 9*18 , 12*20, 12*18, - ถุงใส 6*9 ถุงขยะดำ 24*28*20mm, - ถุงขยะสีชา - ถุงHD A11*17 หนา 0.12มม./คู่ -ถุง HD A 14*25 หนา0.12มม./คู่ -ถุง HD A19*12(แผ่นแพ็ค) - ถุงHD A10*16หนา0.08มม.คู่ไม่พิมพ์โลโก้ - ถุง HD A10*16 หนา พิมพ์โลโก้ - ถุงHD 11*17 พิมพืโลกโก้หมูนมสด Size s - ถุงHD A10*16 พิมพ์ไก่พริกไทยดำ - ถุงHD A10*16 พิมพ์ไก่แดง - ถุงHD A10*16 พิมพ์ไก่นมสด | ระยะเวลาจัดส่ง: 10-14 วัน ทำการ | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น บรรจุภัณฑ์ — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0022';
UPDATE suppliers SET materialCode = 'PK0001, 2, 38, 39', name = 'บริษัท เจเนอรัล เรคคอร์ด อินเตอร์เนชั่นแนล อินดัสตรี้ จำกัด', email = 'Basกล่องลูกฟูก', address = '2/1 หมู่ 2 ต.คลองขวาง อ.ไทรน้อย จ.นนทบุรี', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: กล่องลูกฟูก5ชั้น ขนาด287*385*305 กล่องลูกฟูก5ชั้น ขนาด23*40*21.2 กล่องลูกฟูก5ชั้น ขนาด 230*400*170 กล่องลูกฟูก5ชั้น ขนาด 287*385*185 | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น บรรจุภัณฑ์ — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0023';
UPDATE suppliers SET materialCode = 'PK0010, PK00010', email = 'Au เทปใส', address = '12 ซอยพุทธบูชา 36 ถนนพุทธบูชา แขวงบางมด เขตทุ่งครุ กรุงเทพมหานคร', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: เทปใส | ระยะเวลาจัดส่ง: 20-30 | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น บรรจุภัณฑ์ — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0024';
UPDATE suppliers SET materialCode = 'PK0019, 20, 21, 22, 29', contact = '063-4744466 099-4451616', email = 'กลุ่มไม้เสียบ', address = '129 ซอยรามคำแหง 26/1 แขวงหัวหมาก เขตบางกะปิ กรุงเทพ', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ไม้เสียบ 3*5 ไม้เสียบ 3*6 ไม้เสียบ 3*7 ไม้ชายธงเบอร์6 ไม้กลม2.5*6 | ระยะเวลาจัดส่ง: 7-10วัน | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น บรรจุภัณฑ์ — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0025';
UPDATE suppliers SET materialCode = 'PK0040', contact = '02-9457393-5', email = 'พี่เล็ก(สติ้กเกอร์)', address = '44/108,44/110-113,44/279 หมู่ 8 ถนนรามอินทรา แขวงท่าแร้ง เขตบางเขน กรุงเทพ', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: สติ้กเกอร์ติดข้างกล่องMK สติ้กเกอร์ติดแพ็คเก็จจิ้งMK | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น บรรจุภัณฑ์ — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0026';
UPDATE suppliers SET materialCode = 'CM0002, PG0007', address = '3/101 ม.4 ห้อง 103 ถ.ไสวประชาราษฎร์ ต.ลาดสวาย อ.ลำลูกกา จ.ปทุมธานี 12150', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: คลอรีนน้ำ 10% (โซเดียมไฮโปรคลอไรด์) | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น สารเคมี — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0027';
UPDATE suppliers SET materialCode = 'CM0003, PG0008', address = '42 หมุ่ที่ 1 ต.คุขวาง อ.ลาดหลุมแก้ว จ.ปทุมธานี', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: น้ำยาล้างภาชนะไร้สีไร้กลิ่น15% | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น สารเคมี — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0028';
UPDATE suppliers SET materialCode = 'CM0006, PG0017', email = 'Line : Jakkrit/Flussing', address = '2292,2294,2296 ถนนพัฒนาการ แขวงสวนหลวง เขตสวนหลวง กรุงเทพมหานคร', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ผลิตภัณฑ์ฆ่าเชื้ออเนกประสงค์ | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น สารเคมี — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0029';
UPDATE suppliers SET materialCode = 'PG0012, 13, 14', contact = '02-3222384', address = '14 หมู่บ้านคันทรีวิลล่า ซอย 2 แขวงหนองบอน เขตประเวศ กรุงเทพมหานคร 10250', notes = TRIM(COALESCE(notes,'') || CASE WHEN COALESCE(notes,'')='' THEN '' ELSE ' | ' END || 'สินค้าที่ส่ง: ถุงมือยางสีน้ำเงิน ไซส์ S,M,L | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น เครื่องแต่งกาย — นำเข้า 02/08/69'), modified = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'SP0032';

-- ── Two suppliers the register did not have ─────────────────────────────────
INSERT OR IGNORE INTO suppliers
  (id, name, type, risk, status, materialCode, contact, email, address,
   requiredDocs, notes, created, modified)
VALUES
 ('SP0036', 'บริษัท หมูเจริญ ฟู้ดส์เซอร์วิส จำกัด', 'RM', 'HIGH', 'Inactive',
  'RM0001, RM0002',
  '092-8828692 · คุณหมิง',
  NULL,
  '632/13 ถ.สืบสิริ ต.ในเมือง อ.เมือง จ.นครราชสีมา 30000',
  'ร3., รน. เอกสารรับรองฟาร์ม',
  'สินค้าที่ส่ง: สะโพกหมู มันสันแข็ง | เงื่อนไขชำระเงิน: เครดิต | หมายเหตุในทะเบียน: บริษัทปิดทำการ — จึงบันทึกสถานะเป็น Inactive ไม่ใช่ Approved · คงไว้ในทะเบียนเพื่อให้บันทึกการรับวัตถุดิบย้อนหลังที่อ้างถึงผู้ขายรายนี้มีที่อ้างอิง | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่น RM — นำเข้า 02/08/69',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
 ('SP0037', 'บริษัท ผลธัญญะ จำกัด', 'PM', 'LOW', 'Pending',
  NULL,
  '02-7910111',
  'LINE : Phol Dhanya',
  '1/11 หมู่ 3 ถนนลำลุกกา ต.ลาดสวาย อ.ลำลูกกา จ.ปทุมธานี',
  NULL,
  'สินค้าที่ส่ง: รองเท้าบูทยางสีขาว | ยังไม่มีรหัสสินค้าในทะเบียน — รองเท้าบูทยางเป็นอุปกรณ์สวมใส่ ไม่ใช่บรรจุภัณฑ์ที่สัมผัสอาหาร | สถานะ Pending รอ QA ประเมินและกำหนดขอบเขตที่อนุมัติ | ที่มา: ทะเบียนผู้ขาย (Excel) แผ่นเครื่องแต่งกาย — นำเข้า 02/08/69',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
